// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.mas2022datascience.avro.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class GeneralMatchTeam : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""GeneralMatchTeam"",""namespace"":""com.mas2022datascience.avro.v1"",""fields"":[{""name"":""HomeLongName"",""type"":{""type"":""string"",""avro.java.string"":""String""}},{""name"":""HomeShortName"",""type"":{""type"":""string"",""avro.java.string"":""String""}},{""name"":""HomeTeamID"",""type"":""int""},{""name"":""AwayLongName"",""type"":{""type"":""string"",""avro.java.string"":""String""}},{""name"":""AwayShortName"",""type"":{""type"":""string"",""avro.java.string"":""String""}},{""name"":""AwayTeamID"",""type"":""int""}]}");
		private string _HomeLongName;
		private string _HomeShortName;
		private int _HomeTeamID;
		private string _AwayLongName;
		private string _AwayShortName;
		private int _AwayTeamID;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return GeneralMatchTeam._SCHEMA;
			}
		}
		public string HomeLongName
		{
			get
			{
				return this._HomeLongName;
			}
			set
			{
				this._HomeLongName = value;
			}
		}
		public string HomeShortName
		{
			get
			{
				return this._HomeShortName;
			}
			set
			{
				this._HomeShortName = value;
			}
		}
		public int HomeTeamID
		{
			get
			{
				return this._HomeTeamID;
			}
			set
			{
				this._HomeTeamID = value;
			}
		}
		public string AwayLongName
		{
			get
			{
				return this._AwayLongName;
			}
			set
			{
				this._AwayLongName = value;
			}
		}
		public string AwayShortName
		{
			get
			{
				return this._AwayShortName;
			}
			set
			{
				this._AwayShortName = value;
			}
		}
		public int AwayTeamID
		{
			get
			{
				return this._AwayTeamID;
			}
			set
			{
				this._AwayTeamID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.HomeLongName;
			case 1: return this.HomeShortName;
			case 2: return this.HomeTeamID;
			case 3: return this.AwayLongName;
			case 4: return this.AwayShortName;
			case 5: return this.AwayTeamID;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.HomeLongName = (System.String)fieldValue; break;
			case 1: this.HomeShortName = (System.String)fieldValue; break;
			case 2: this.HomeTeamID = (System.Int32)fieldValue; break;
			case 3: this.AwayLongName = (System.String)fieldValue; break;
			case 4: this.AwayShortName = (System.String)fieldValue; break;
			case 5: this.AwayTeamID = (System.Int32)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
        public bool ShouldSerializeSchema()
        {
            //only serialize Schema if SerializeSensitiveInfo == true
            return (false);
        }
    }
}
