// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.mas2022datascience.avro.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Object : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Object"",""namespace"":""com.mas2022datascience.avro.v1"",""fields"":[{""name"":""type"",""type"":{""type"":""int"",""description"":""type can be 0 (home), 1 (away) and 7 (ball)""}},{""name"":""id"",""type"":{""type"":""string"",""avro.java.string"":""String"",""description"":""player id or jersey number""}},{""name"":""playerId"",""default"":null,""type"":[""null"",{""type"":""string"",""avro.java.string"":""String""}]},{""name"":""teamId"",""default"":null,""type"":[""null"",{""type"":""string"",""avro.java.string"":""String""}]},{""name"":""zone"",""default"":null,""type"":[""null"",""int""]},{""name"":""x"",""type"":{""type"":""int"",""description"":""x coordinate""}},{""name"":""y"",""type"":{""type"":""int"",""description"":""y coordinate""}},{""name"":""z"",""type"":{""type"":""int"",""description"":""z coordinate""}},{""name"":""sampling"",""type"":""int""},{""name"":""velocity"",""default"":null,""type"":[""null"",""double""]},{""name"":""accelleration"",""default"":null,""type"":[""null"",""double""]},{""name"":""distance"",""default"":null,""type"":[""null"",""double""]},{""name"":""delta_time"",""default"":null,""type"":[""null"",""double""]}]}");
		private int _type;
		private string _id;
		private string _playerId;
		private string _teamId;
		private System.Nullable<System.Int32> _zone;
		private int _x;
		private int _y;
		private int _z;
		private int _sampling;
		private System.Nullable<System.Double> _velocity;
		private System.Nullable<System.Double> _accelleration;
		private System.Nullable<System.Double> _distance;
		private System.Nullable<System.Double> _delta_time;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Object._SCHEMA;
			}
		}
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string playerId
		{
			get
			{
				return this._playerId;
			}
			set
			{
				this._playerId = value;
			}
		}
		public string teamId
		{
			get
			{
				return this._teamId;
			}
			set
			{
				this._teamId = value;
			}
		}
		public System.Nullable<System.Int32> zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				this._zone = value;
			}
		}
		public int x
		{
			get
			{
				return this._x;
			}
			set
			{
				this._x = value;
			}
		}
		public int y
		{
			get
			{
				return this._y;
			}
			set
			{
				this._y = value;
			}
		}
		public int z
		{
			get
			{
				return this._z;
			}
			set
			{
				this._z = value;
			}
		}
		public int sampling
		{
			get
			{
				return this._sampling;
			}
			set
			{
				this._sampling = value;
			}
		}
		public System.Nullable<System.Double> velocity
		{
			get
			{
				return this._velocity;
			}
			set
			{
				this._velocity = value;
			}
		}
		public System.Nullable<System.Double> accelleration
		{
			get
			{
				return this._accelleration;
			}
			set
			{
				this._accelleration = value;
			}
		}
		public System.Nullable<System.Double> distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				this._distance = value;
			}
		}
		public System.Nullable<System.Double> delta_time
		{
			get
			{
				return this._delta_time;
			}
			set
			{
				this._delta_time = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.type;
			case 1: return this.id;
			case 2: return this.playerId;
			case 3: return this.teamId;
			case 4: return this.zone;
			case 5: return this.x;
			case 6: return this.y;
			case 7: return this.z;
			case 8: return this.sampling;
			case 9: return this.velocity;
			case 10: return this.accelleration;
			case 11: return this.distance;
			case 12: return this.delta_time;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.type = (System.Int32)fieldValue; break;
			case 1: this.id = (System.String)fieldValue; break;
			case 2: this.playerId = (System.String)fieldValue; break;
			case 3: this.teamId = (System.String)fieldValue; break;
			case 4: this.zone = (System.Nullable<System.Int32>)fieldValue; break;
			case 5: this.x = (System.Int32)fieldValue; break;
			case 6: this.y = (System.Int32)fieldValue; break;
			case 7: this.z = (System.Int32)fieldValue; break;
			case 8: this.sampling = (System.Int32)fieldValue; break;
			case 9: this.velocity = (System.Nullable<System.Double>)fieldValue; break;
			case 10: this.accelleration = (System.Nullable<System.Double>)fieldValue; break;
			case 11: this.distance = (System.Nullable<System.Double>)fieldValue; break;
			case 12: this.delta_time = (System.Nullable<System.Double>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
        public bool ShouldSerializeSchema()
        {
            //only serialize Schema if SerializeSensitiveInfo == true
            return (false);
        }
    }
}
