// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.mas2022datascience.avro.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class TracabGen5TF01 : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TracabGen5TF01\",\"namespace\":\"com.mas2022datascience.avro" +
				".v1\",\"fields\":[{\"name\":\"utc\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"" +
				"}},{\"name\":\"ts\",\"default\":null,\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"time" +
				"stamp-millis\"}]},{\"name\":\"matchId\",\"default\":null,\"type\":[\"null\",{\"type\":\"string" +
				"\",\"avro.java.string\":\"String\"}]},{\"name\":\"isBallInPlay\",\"type\":{\"type\":\"string\"," +
				"\"avro.java.string\":\"String\",\"description\":\"Ball status or BallInPlay, [D is Dead" +
				", A is Alive]\"}},{\"name\":\"ballPossession\",\"type\":{\"type\":\"string\",\"avro.java.str" +
				"ing\":\"String\",\"description\":\"Who has ball possession [Home, Away]\"}},{\"name\":\"co" +
				"ntactDevInfo\",\"default\":null,\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":" +
				"\"String\"}]},{\"name\":\"objects\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"n" +
				"ame\":\"Object\",\"namespace\":\"com.mas2022datascience.avro.v1\",\"fields\":[{\"name\":\"ty" +
				"pe\",\"type\":{\"type\":\"int\",\"description\":\"type can be 0 (home), 1 (away) and 7 (ba" +
				"ll)\"}},{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"descrip" +
				"tion\":\"player id or jersey number\"}},{\"name\":\"playerId\",\"default\":null,\"type\":[\"" +
				"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"teamId\",\"default\"" +
				":null,\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"zo" +
				"ne\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"x\",\"type\":{\"type\":\"int\",\"desc" +
				"ription\":\"x coordinate\"}},{\"name\":\"y\",\"type\":{\"type\":\"int\",\"description\":\"y coor" +
				"dinate\"}},{\"name\":\"z\",\"type\":{\"type\":\"int\",\"description\":\"z coordinate\"}},{\"name" +
				"\":\"sampling\",\"type\":\"int\"},{\"name\":\"velocity\",\"default\":null,\"type\":[\"null\",\"dou" +
				"ble\"]},{\"name\":\"accelleration\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":" +
				"\"distance\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"delta_time\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"double\"]}]}}}]}");
		private string _utc;
		private System.Nullable<System.DateTime> _ts;
		private string _matchId;
		private string _isBallInPlay;
		private string _ballPossession;
		private string _contactDevInfo;
		private IList<com.mas2022datascience.avro.v1.Object> _objects;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return TracabGen5TF01._SCHEMA;
			}
		}
		public string utc
		{
			get
			{
				return this._utc;
			}
			set
			{
				this._utc = value;
			}
		}
		public System.Nullable<System.DateTime> ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				this._ts = value;
			}
		}
		public string matchId
		{
			get
			{
				return this._matchId;
			}
			set
			{
				this._matchId = value;
			}
		}
		public string isBallInPlay
		{
			get
			{
				return this._isBallInPlay;
			}
			set
			{
				this._isBallInPlay = value;
			}
		}
		public string ballPossession
		{
			get
			{
				return this._ballPossession;
			}
			set
			{
				this._ballPossession = value;
			}
		}
		public string contactDevInfo
		{
			get
			{
				return this._contactDevInfo;
			}
			set
			{
				this._contactDevInfo = value;
			}
		}
		public IList<com.mas2022datascience.avro.v1.Object> objects
		{
			get
			{
				return this._objects;
			}
			set
			{
				this._objects = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.utc;
			case 1: return this.ts;
			case 2: return this.matchId;
			case 3: return this.isBallInPlay;
			case 4: return this.ballPossession;
			case 5: return this.contactDevInfo;
			case 6: return this.objects;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.utc = (System.String)fieldValue; break;
			case 1: this.ts = (System.Nullable<System.DateTime>)fieldValue; break;
			case 2: this.matchId = (System.String)fieldValue; break;
			case 3: this.isBallInPlay = (System.String)fieldValue; break;
			case 4: this.ballPossession = (System.String)fieldValue; break;
			case 5: this.contactDevInfo = (System.String)fieldValue; break;
			case 6: this.objects = (IList<com.mas2022datascience.avro.v1.Object>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
        public bool ShouldSerializeSchema()
        {
            //only serialize Schema if SerializeSensitiveInfo == true
            return (false);
        }
    }
}
